/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        white: '#ffffff',
        gray: {
          50: 'var(--gray-50)',
          100: 'var(--gray-100)',
          200: 'var(--gray-200)',
          300: 'var(--gray-300)',
          400: 'var(--gray-400)',
          500: 'var(--gray-500)',
          600: 'var(--gray-600)',
          700: 'var(--gray-700)',
          800: 'var(--gray-800)',
          900: 'var(--gray-900)',
        },
        brand: {
          primary: 'rgb(var(--primary-rgb) / <alpha-value>)',
          'primary-dark': 'rgb(var(--primary-dark-rgb) / <alpha-value>)',
          'primary-light': 'rgb(var(--primary-light-rgb) / <alpha-value>)',
          bg: 'rgb(var(--primary-bg-rgb) / <alpha-value>)',
        },
        surface: {
          DEFAULT: 'var(--surface)',
          elevated: 'var(--surface-elevated)',
          raised: 'var(--surface-raised)',
        },
        ink: {
          primary: 'var(--gray-900)',
          secondary: 'var(--text-secondary)',
          muted: 'var(--text-muted)',
        },
        state: {
          success: 'rgb(var(--success-rgb) / <alpha-value>)',
          'success-bg': 'var(--success-bg)',
          'success-border': 'var(--success-border)',
          'success-strong': 'rgb(var(--success-strong-rgb) / <alpha-value>)',
          warning: 'rgb(var(--warning-rgb) / <alpha-value>)',
          'warning-bg': 'var(--warning-bg)',
          'warning-border': 'var(--warning-border)',
          'warning-strong': 'rgb(var(--warning-strong-rgb) / <alpha-value>)',
          info: 'rgb(var(--info-rgb) / <alpha-value>)',
          'info-bg': 'var(--info-bg)',
          'info-border': 'var(--info-border)',
          'info-strong': 'rgb(var(--info-strong-rgb) / <alpha-value>)',
          danger: 'rgb(var(--danger-rgb) / <alpha-value>)',
          'danger-bg': 'var(--danger-bg)',
          'danger-strong': 'rgb(var(--danger-strong-rgb) / <alpha-value>)',
          purple: 'rgb(var(--purple-rgb) / <alpha-value>)',
          'purple-bg': 'var(--purple-bg)',
          'purple-border': 'var(--purple-border)',
          'purple-strong': 'rgb(var(--purple-strong-rgb) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
        mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      borderRadius: {
        DEFAULT: 'var(--radius)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-lg)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-lg)',
      },
    },
  },
  plugins: [],
};
